### ISSUE TITLE
你好，你也是大气所学生吗？

### ISSUE THREAD

**Issue by PhilosopherZ** [Rainbow1994/Ensemble_driver#1]
你好，你也是大气所学生吗？哈哈

**Comment by Rainbow1994** [comment]
对！



---------------------------

Rainbow | Sihong Zhu

visiting Ph.D. student

School of Geosciences, The University of Edinburgh

Room Attic, Crew Building, The Kings Buildings, Alexander Crum Brown Road

Edinburgh, EH9 3FF

在2020年11月25日 10:57，Zhangzhe<notifications@github.com> 写道：

你好，你也是大气所学生吗？哈哈

**Comment by PhilosopherZ** [comment]
这不是微信，瞬间回复哈哈，现在还在读博士？

**Comment by Rainbow1994** [comment]
是呢！你也是博士在读吗？




在2020年11月25日 11:00，Zhangzhe<notifications@github.com> 写道：

现在还在读博士？

**Comment by PhilosopherZ** [comment]
> 是呢！你也是博士在读吗？ 在2020年11月25日 11:00，Zhangzhe<notifications@github.com> 写道： 现在还在读博士？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
是的啊

**Comment by PhilosopherZ** [comment]
> 是呢！你也是博士在读吗？ 在2020年11月25日 11:00，Zhangzhe<notifications@github.com> 写道： 现在还在读博士？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你现在在英国读博的吗？

**Comment by Rainbow1994** [comment]
交流呢，还是大气所学生。
在2020年11月25日 11:12，Zhangzhe<notifications@github.com> 写道：

是呢！你也是博士在读吗？ 在2020年11月25日 11:00，Zhangzhenotifications@github.com 写道： 现在还在读博士？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你现在在英国读博的吗？

**Comment by PhilosopherZ** [comment]
嗯嗯，可以认识下哈




> 交流呢，还是大气所学生。 在2020年11月25日 11:12，Zhangzhe<notifications@github.com> 写道： 是呢！你也是博士在读吗？ 在2020年11月25日 11:00，Zhangzhenotifications@github.com 写道： 现在还在读博士？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你现在在英国读博的吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Rainbow1994** [comment]
可以可以，都是朋友嘛。




在2020年11月25日 11:20，Zhangzhe<notifications@github.com> 写道：

嗯嗯，可以认识下哈

交流呢，还是大气所学生。 在2020年11月25日 11:12，Zhangzhenotifications@github.com 写道： 是呢！你也是博士在读吗？ 在2020年11月25日 11:00，Zhangzhenotifications@github.com 写道： 现在还在读博士？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你现在在英国读博的吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by PhilosopherZ** [comment]
> 可以可以，都是朋友嘛。 在2020年11月25日 11:20，Zhangzhe<notifications@github.com> 写道： 嗯嗯，可以认识下哈 交流呢，还是大气所学生。 在2020年11月25日 11:12，Zhangzhenotifications@github.com 写道： 是呢！你也是博士在读吗？ 在2020年11月25日 11:00，Zhangzhenotifications@github.com 写道： 现在还在读博士？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你现在在英国读博的吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

呃，那加个微信？github真成交友网站啦(捂脸）

**Comment by Rainbow1994** [comment]
好的呀！qiurisiyu325 你搜一下。








在2020年11月25日 11:34，Zhangzhe<notifications@github.com> 写道：

可以可以，都是朋友嘛。 在2020年11月25日 11:20，Zhangzhenotifications@github.com 写道： 嗯嗯，可以认识下哈 交流呢，还是大气所学生。 在2020年11月25日 11:12，Zhangzhenotifications@github.com 写道： 是呢！你也是博士在读吗？ 在2020年11月25日 11:00，Zhangzhenotifications@github.com 写道： 现在还在读博士？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你现在在英国读博的吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

呃，那加个微信？github真成交友网站啦(捂脸）
